apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cloudops-cluster-eks
  region: us-east-1

vpc:
  id: vpc-0cf640cf3c2a608d6
  subnets:
    public:
      us-east-1a:
        id: subnet-01e563b642ddb3383
      us-east-1b:
        id: subnet-06ea7a7cff49f8506
    private:
      us-east-1a:
        id: subnet-0de9f62039626afe1
      us-east-1b:
        id: subnet-01073b7d598d3295d

fargateProfiles:
  - name: default
    selectors:
      - namespace: default
      - namespace: kube-system
