apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cloudops-cluster-eks
  region: us-east-1

vpc:
  id: vpc-077d27d9a112d19d0
  subnets:
    public:
      us-east-1a:
        id: subnet-0e2d0a1a945e86870
      us-east-1b:
        id: subnet-0a355f3953d30d5ed
    private:
      us-east-1a:
        id: subnet-0c4b81e63c9d3db3f
      us-east-1b:
        id: subnet-042b4a91c6706da66

fargateProfiles:
  - name: default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: monitoring
      - namespace: argocd  
