apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: default
  labels:
    app: {{ .Release.Name }}-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::326709068429:role/cloudops-ecs-task-role
